# Theme settings
# ä¸»é¢˜è®¾ç½®
# use CDN to boost your site(CDN Providers:true(use jsdelivr)/cdnjs/jsdelivr/staticfile/bootcdn/bytedance/unpkg/false(won't use CDN))
# ä½¿ç”¨CDNåŠ é€Ÿå‰ç«¯è½½å…¥(CDNæä¾›å•†:true(ä½¿ç”¨é»˜è®¤çš„jsdelivr)/cdnjs/jsdelivr/staticfile/bootcdn/bytedance/unpkg/false(ä¸ä½¿ç”¨CDN))
cdn_provider: 'bootcdn'

# ä½¿ç”¨ç‰¹å®šçš„MDUIåº“ç‰ˆæœ¬(é»˜è®¤1.0.2ï¼Œæ‚¨å¯ä»¥æ‰‹åŠ¨ä¿®æ”¹ä¸ºå…¶ä»–ç‰ˆæœ¬)
# Use a specific MIUI version(default:1.0.2, you can modify it to other versions manually)
# æ³¨æ„ï¼šä¸ä½¿ç”¨CDNæ—¶è¯·å°†è¿™é¡¹ç•™ç©ºæˆ–è€…å¡«å†™1.0.2ï¼Œå¦åˆ™ä¼šå‡ºç°é”™è¯¯
# Note: Please leave this blank or fill in 1.0.2 when not using CDN, otherwise an error will occur
mdui_version:  

# Theme colors
# Check out all the colors here: https://www.mdui.org/docs/color
# ä¸»é¢˜é¢œè‰²
# é¢œè‰²åˆ—è¡¨è¯·çœ‹: https://www.mdui.org/docs/color
color:
  primary: indigo
  accent: pink

# GPDR Cookie alert(HTML Tag supported)
# This will show a snackbar at the right bottom of the page
# GPDR Cookieæç¤º(æ”¯æŒHTMLæ ‡ç­¾)
# æ•ˆæœæ˜¯é¡µé¢å³ä¸‹è§’æ˜¾ç¤ºä¸€ä¸ªSnackbar
gdpr_cookie_alert:
  enable: true
  # å¦‚éœ€äº«å—MDxçš„i18nåŠŸèƒ½ï¼Œè¯·å°†ä¸‹é¢ä¸¤ä¸ªé€‰é¡¹ç•™ç©º
  # If you want to use MDx's i18n feature, please leave them blank
  # æç¤ºæ–‡å­—
  text: æ­¤ç½‘ç«™ä½¿ç”¨Cookieæ¥æ”¹å–„æ‚¨çš„ä½“éªŒã€‚
  # æŒ‰é’®æ–‡å­—
  # Button text
  ack_btn: Got it

# Check user's online status
# If you use Service-Worker, etc. in offline mode, you can still read articles, but cannot comment, etc, then this option will be very useful
# MDx will check network connection each 5 secs, and show an alert when network is disconnected.
# æ£€æŸ¥ç”¨æˆ·åœ¨çº¿çŠ¶æ€
# å¦‚æœæ‚¨ç”¨äº†Service-Workerç­‰æŠ€æœ¯åœ¨æ— ç½‘ç»œæ—¶ä¹Ÿèƒ½é˜…è¯»æ–‡ç« ï¼Œä½†æ˜¯æ— æ³•è¿›è¡Œè¯„è®ºç­‰æ“ä½œï¼Œé‚£ä¹ˆæ­¤é€‰é¡¹å°†éå¸¸æœ‰ç”¨
# å¯ç”¨åMDxä¼šæ¯éš”5ç§’æ£€æµ‹ä¸€æ¬¡ç½‘ç»œè¿æ¥ï¼Œå¹¶åœ¨ä¸¢å¤±ç½‘ç»œè¿æ¥æ—¶æ˜¾ç¤ºä¸€æ¡æç¤ºã€‚
online_check:
  enable: true
  # å¦‚éœ€äº«å—MDxçš„i18nåŠŸèƒ½ï¼Œè¯·å°†ä¸‹é¢ä¸¤ä¸ªé€‰é¡¹ç•™ç©º
  # If you want to use MDx's i18n feature, please leave them blank
  # Offline alert text(optional)
  # ç¦»çº¿æ—¶æç¤ºçš„æ–‡å­—(å¯é€‰)
  offlineText: æ‚¨ä¼¼ä¹å¤„äºç¦»çº¿çŠ¶æ€ï¼ŒæŸäº›åŠŸèƒ½æ— æ³•ä½¿ç”¨ï¼Œè¯·æ£€æŸ¥æ‚¨çš„ç½‘ç»œè¿æ¥ã€‚
  # Online alert text(optional)
  # ç½‘ç»œè¿æ¥æ¢å¤æ—¶æç¤ºçš„æ–‡å­—(å¯é€‰)
  onlineText: ç½‘ç»œè¿æ¥å·²æ¢å¤ï¼
  ack_btn: äº†è§£

# Link to header picture
header_picture_link: # å¤´å›¾é“¾æ¥
# Link to favicon.ico
favicon: # ç½‘ç«™å›¾æ ‡é“¾æ¥
# Auto-generated excerpt length, <!-- more --> is supported
excerpt_length: 250 # è‡ªåŠ¨ç”Ÿæˆçš„æ‘˜è¦é•¿åº¦ï¼Œ<!-- more -->ä¹Ÿæ”¯æŒ

# Search settings(depends on "hexo-generator-search")
# Need to be configured in JSON format, the path is '/search.json'
# æœç´¢è®¾ç½®(ä¾èµ– "hexo-generator-search")
# éœ€é…ç½®ä¸ºJSONæ ¼å¼ï¼Œè·¯å¾„ä¸º'/search.json'
search:
  # Enable search
  # æ˜¯å¦å¯ç”¨æœç´¢åŠŸèƒ½
  enable: true
  # Search database path(default: './search.json')
  # æœç´¢æ•°æ®åº“è·¯å¾„(é»˜è®¤ä¸º'/search.json')
  path: /search.json
  # å¦‚éœ€äº«å—MDxçš„i18nåŠŸèƒ½ï¼Œè¯·å°†ä¸‹é¢ç•™ç©º
  # If you want to use MDx's i18n feature, please leave them blank
  # Search box placeholder text(optional)
  # æœç´¢æ¡†æç¤ºæ–‡å­—(å¯é€‰)
  placeholder: æœç‚¹ä»€ä¹ˆ...
  # No result text($txt$ will be replaced with the search content)(optional)
  # æ— ç»“æœæ—¶æ˜¾ç¤ºçš„æ–‡å­—($txt$ä¼šè¢«æ›¿æ¢ä¸ºæœç´¢çš„å†…å®¹)(å¯é€‰)
  no_result: æ²¡æœ‰æ‰¾åˆ°ä¸â€œ$txt$â€ç›¸å…³çš„æ–‡ç« 
  # Search database load error text(optional)
  # æœç´¢æ•°æ®åº“åŠ è½½é”™è¯¯æ—¶æ˜¾ç¤ºçš„æ–‡å­—(å¯é€‰)
  error: MDxçš„æœç´¢æ•°æ®åº“ä¼¼ä¹æœªæ­£ç¡®åŠ è½½ï¼Œè¯·å°è¯•åˆ·æ–°é¡µé¢

# About field at the drawer menu
# æŠ½å±‰èœå•çš„å…³äºæ 
drawer_about:
  enable: true
  # Link to avatar image
  avatar: https://cos-us-west.wtbs.ml/fe0d50b463e74f3ab280de0cf9425b67.png # å¤´åƒé“¾æ¥
  # Name
  name: # åå­—
  # Slogan
  slogan: å¹´å¹´å²å²èŠ±ç›¸ä¼¼ï¼Œå²å²å¹´å¹´äººä¸åŒ # æ ‡è¯­ï¼ˆä¸ªæ€§ç­¾åï¼‰
  # Link to background image
  background:  https://cos-us-west.wtbs.ml/3-210526154Z0.jpg # èƒŒæ™¯å›¾ç‰‡é“¾æ¥
  # Whether the background is dark-colored or not
  is_dark: true # èƒŒæ™¯å›¾æ˜¯ä¸æ˜¯æ·±è‰²çš„

# Drawer menu list (Nested lists are not supported)
# Format: Link name: Link || Icon
# Check out all the icons at https://www.mdui.org/docs/material_icon
# æŠ½å±‰èœå•åˆ—è¡¨ï¼ˆæš‚ä¸æ”¯æŒåµŒå¥—åˆ—è¡¨ï¼‰
# æ ¼å¼: åç§°: é“¾æ¥ || å›¾æ ‡
# å›¾æ ‡åˆ° https://www.mdui.org/docs/material_icon æ‰¾
drawer:
  ä¸»é¡µ: / || &#xe88a;
  MDx: https://github.com/Yuameshi/hexo-theme-mdx || &#xe243;
  GitHub: https://github.com/NoctuG || &#xe149;
  å…³äº: /about || &#xe88e;

# Text which will inserted at the end of the article.
# '%title%' refers to title link of current post.
# '%link%' refers to permalink link of current post
# æ–‡ç« æœ«å°¾æ’å…¥çš„æ–‡æ®µï¼Œ%title%è¡¨ç¤ºæ–‡ç« æ ‡é¢˜ï¼Œ%link%è¡¨ç¤ºæ–‡ç« é“¾æ¥
passage_end_tag:
  enabled: true
  text: 'END'

# Comment system settings
# è¯„è®ºç³»ç»Ÿ
comment:
  use: utterances
  # gitalk configuration refers to https://github.com/gitalk/gitalk/
  # Gitalké…ç½®æ–‡æ¡£ï¼šhttps://github.com/gitalk/gitalk/
  gitalk:
    clientID: 
    clientSecret: 
    repo: 
    owner: 
    admin: ['']
    distractionFreeMode: true
  # utterance configuration refers to https://utteranc.es/
  # utterancé…ç½®æ–‡æ¡£ï¼šhttps://utteranc.es/
  utterances:
    repo: NoctuG/mlou
    issue_term: pathname
    lable: ğŸŒ
    theme: dark-blue

# ç½‘é¡µåˆ†æ
analytics:
  # Google Analytics configuration refers to https://analytics.google.com/
  # Google Analyticså®˜ç½‘ï¼šhttps://analytics.google.com/
  google:
    enabled: false
    tracking_id: 
  # Cloudflare Web Analytics configuration refers to https://developers.cloudflare.com/analytics/web-analytics
  # Cloudflare Web Analyticsæ–‡æ¡£ï¼šhttps://developers.cloudflare.com/analytics/web-analytics
  cloudflare:
    enabled: false
    token: 

footer:
  # When the site was launched
  since: 2022-6-17 # ç«™ç‚¹å¼€å§‹è¿è¥æ—¶é—´
  # Show 'Â© %SITE_NAME%' in footer
  copyrights: true # ä¼šåœ¨é¡µè„šæ˜¾ç¤º 'Â© %SITE_NAME%'
  # Show "Powered by Hexo" in the footer
  hexo: true # ä¼šåœ¨é¡µè„šæ˜¾ç¤º 'Powered by Hexo'
  # Show "Themed MDx" in footer
  theme: true # ä¼šåœ¨é¡µè„šæ˜¾ç¤º 'ç”± MDx ä¸»é¢˜è£…é¥°'ï¼ˆçƒçƒäº†å¼€å¼€å§ï¼‰
  # Text to show on the footer
  text: # ä¼šåœ¨é¡µè„šæ˜¾ç¤º 'è‡ªå®šä¹‰çš„æ–‡å­—'
  # Social media links
  contact: # ä¼šåœ¨é¡µè„šæ˜¾ç¤ºé“¾æ¥
    MDx: https://github.com/Yuameshi/hexo-theme-mdx
    GitHub: https://github.com/NoctuG
  # Link to MIIT ICP
  miit_icp: # ä¼šåœ¨é¡µè„šæ˜¾ç¤ºå¤‡æ¡ˆå·
  # Link to MOE ICP
  moe_icp: # ä¼šåœ¨é¡µè„šæ˜¾ç¤ºèŒå¤‡
