version: 1654266144177
language: cn
aomori_widgets:
  - toc
  - category
  - tag
  - recent_posts
  - archive
 aomori_logo_typed_animated: true
 aomori_menu:
  é¦–é¡µ: /
  å…³äº: /about
  å‹é“¾: /friends
  
 aomori_widgets:
  - toc # æ–‡ç« å¯¼èˆª
  - categories  #æ–‡ç« åˆ†ç±»
  - tags # æ–‡ç« æ ‡ç­¾
  - recent_posts  # æœ€æ–°æ–‡ç« 
  - archive #æ–‡ç« å½’æ¡£
 aomori_disqusjs:
  enable: true
  shortname: "noctu"
  siteName: ""
  api: "L8dNhdYfskL7wNHr0fCBrdxZhEdvvHh2cyH9kpGJEWsjDaGDlr2HpZp4EyEL0cxx"
  apikey: "3ptZSdaVDbp92GUdUtV6dgzXQNjfdoRD3wv3sGDQVbBxOFgu1LbDh1sXMB66GxzW"
  nesting: 4
  nocomment: "è¿™é‡Œå†·å†·æ¸…æ¸…çš„ï¼Œä¸€æ¡è¯„è®ºéƒ½æ²¡æœ‰"
  admin: "disqus_a85BDVqBim"
  adminLabel: ""
 aomori_busuanzi: true
 aomori_favicon: ğŸŒ